-- 코드를 입력하세요
WITH q as (
    SELECT a.MEMBER_ID, COUNT(*)
    FROM REST_REVIEW a LEFT JOIN MEMBER_PROFILE b ON a.MEMBER_ID = b.MEMBER_ID
    GROUP BY a.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
    )
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW a LEFT JOIN MEMBER_PROFILE b ON a.MEMBER_ID = b.MEMBER_ID
WHERE a.MEMBER_ID = (SELECT MEMBER_ID FROM q)
ORDER BY REVIEW_DATE, REVIEW_TEXT;