-- 코드를 입력하세요
SELECT DISTINCT a.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a 
     LEFT JOIN CAR_RENTAL_COMPANY_CAR b
     ON a.CAR_ID = b.CAR_ID
WHERE MONTH(a.START_DATE) = '10' AND b.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;