-- 코드를 입력하세요
SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT a
WHERE PRICE = (
        SELECT MAX(PRICE) MAX_PRICE
        FROM FOOD_PRODUCT b
        WHERE b.CATEGORY = a.CATEGORY)
HAVING CATEGORY IN ('과자', '국', '김치','식용유')
ORDER BY MAX_PRICE DESC;
