-- 코드를 입력하세요
SELECT YEAR(a.SALES_DATE) YEAR, MONTH(a.SALES_DATE) MONTH, b.GENDER, COUNT(DISTINCT a.USER_ID) USERS
FROM ONLINE_SALE a LEFT JOIN USER_INFO b ON a.USER_ID = b.USER_ID
WHERE b.GENDER IS NOT NULL
GROUP BY YEAR(a.SALES_DATE), MONTH(a.SALES_DATE), b.GENDER
ORDER BY YEAR, MONTH, GENDER