-- 코드를 입력하세요
SELECT a.CAR_ID, b.CAR_TYPE, FLOOR(b.DAILY_FEE * 30 * (1 - c.DISCOUNT_RATE / 100)) FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
lEFT JOIN CAR_RENTAL_COMPANY_CAR b ON a.CAR_ID = b.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c ON b.CAR_TYPE = c.CAR_TYPE AND c.DURATION_TYPE LIKE '30%'
WHERE b.CAR_TYPE IN ('세단', 'SUV')
    AND a.CAR_ID NOT IN (SELECT CAR_ID 
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                         WHERE START_DATE <= '2022-11-30'
                         AND END_DATE >= '2022-11-01')
GROUP BY a.CAR_ID, b.CAR_TYPE, FLOOR(b.DAILY_FEE * 30 * (1 - c.DISCOUNT_RATE / 100))
HAVING FEE >= 500000 AND FEE < 2000000 
ORDER BY FEE DESC, b.CAR_TYPE, a.CAR_ID DESC