-- 코드를 입력하세요
SELECT a.REST_ID, b.REST_NAME, b.FOOD_TYPE, b.FAVORITES, b.ADDRESS, ROUND(AVG(a.REVIEW_SCORE), 2) SCORE
FROM REST_REVIEW a LEFT JOIN REST_INFO b ON a.REST_ID = b.REST_ID
WHERE b.ADDRESS LIKE '서울%'
GROUP BY a.REST_ID
ORDER BY SCORE DESC, b.FAVORITES DESC;