-- 코드를 입력하세요
SELECT YEAR(b.SALES_DATE) YEAR, MONTH(b.SALES_DATE) MONTH,
       COUNT(DISTINCT b.USER_ID) PURCHASED_USERS,
       ROUND(COUNT(DISTINCT b.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) PURCHASED_RATIO
FROM USER_INFO a JOIN ONLINE_SALE b ON a.USER_ID = b.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;