-- 코드를 입력하세요
SELECT b.AUTHOR_ID, c.AUTHOR_NAME, b.CATEGORY, SUM(a.SALES * b.PRICE) TOTAL_SALES
FROM BOOK_SALES a LEFT JOIN BOOK b ON a.BOOK_ID = b.BOOK_ID
    LEFT JOIN AUTHOR c ON b.AUTHOR_ID = c.AUTHOR_ID
WHERE a.SALES_DATE LIKE '2022-01%'
GROUP BY b.AUTHOR_ID, c.AUTHOR_NAME, b.CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC;