-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', a.BOARD_ID, '/', a.FILE_ID, a.FILE_NAME, a.FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE a LEFT JOIN USED_GOODS_BOARD b ON a.BOARD_ID = b.BOARD_ID
WHERE b.VIEWS = (SELECT MAX(VIEWS)
                 FROM USED_GOODS_BOARD)
ORDER BY a.FILE_ID DESC