-- 코드를 입력하세요
SELECT a.APNT_NO, b.PT_NAME, a.PT_NO, a.MCDP_CD, c.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a LEFT JOIN PATIENT b ON a.PT_NO = b.PT_NO
LEFT JOIN DOCTOR c ON a.MDDR_ID = c.DR_ID
WHERE DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND a.MCDP_CD = 'CS' AND a.APNT_CNCL_YMD IS NULL
ORDER BY a.APNT_YMD