SELECT c.HISTORY_ID,
       FLOOR(c.DAILY_FEE * (DATEDIFF(c.END_DATE, c.START_DATE) + 1) * (1 - COALESCE(d.DISCOUNT_RATE, 0) / 100)) FEE
FROM (
    SELECT a.HISTORY_ID, a.CAR_ID, a.START_DATE, a.END_DATE,
           b.CAR_TYPE, b.DAILY_FEE,
           CASE WHEN DATEDIFF(a.END_DATE, a.START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(a.END_DATE, a.START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(a.END_DATE, a.START_DATE) + 1 >= 7 THEN '7일 이상'
           END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
    LEFT JOIN CAR_RENTAL_COMPANY_CAR b ON a.CAR_ID = b.CAR_ID
    WHERE b.CAR_TYPE = '트럭'
) c
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d 
ON c.CAR_TYPE = d.CAR_TYPE 
AND c.DURATION_TYPE = d.DURATION_TYPE
ORDER BY FEE DESC, c.HISTORY_ID DESC;