-- 코드를 입력하세요

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO a
WHERE FAVORITES = (
        SELECT MAX(FAVORITES)
        FROM REST_INFO b
        WHERE b.FOOD_TYPE = a.FOOD_TYPE)
ORDER BY FOOD_TYPE DESC