SELECT a.EMP_NO, a.EMP_NAME, CASE WHEN AVG(c.SCORE) >= 96 THEN 'S' WHEN AVG(c.SCORE) >= 90 THEN 'A' WHEN AVG(c.SCORE) >= 80 THEN 'B' ELSE 'C' END GRADE,
       CASE WHEN AVG(c.SCORE) >= 96 THEN a.SAL * 0.2 WHEN AVG(c.SCORE) >= 90 THEN a.SAL * 0.15 WHEN AVG(c.SCORE) >= 80 THEN a.SAL * 0.1 ELSE 0 END BONUS
FROM HR_EMPLOYEES a LEFT JOIN HR_DEPARTMENT b ON a.DEPT_ID = b.DEPT_ID
LEFT JOIN HR_GRADE c ON a.EMP_NO = c.EMP_NO
GROUP BY a.EMP_NO, a.EMP_NAME
ORDER BY a.EMP_NO;