-- 코드를 입력하세요
SELECT a.FLAVOR
FROM FIRST_HALF a LEFT JOIN
    (SELECT FLAVOR, SUM(TOTAL_ORDER) JULY_SUM
     FROM JULY
     GROUP BY FLAVOR
    ) b ON a.FLAVOR = b.FLAVOR
ORDER BY a.TOTAL_ORDER + b.JULY_SUM DESC
LIMIT 3;